### ISSUE TITLE
Bug; KeyError: '1'

### ISSUE THREAD

**Issue by RoelVdP** [hgascon/pulsar#15]
```
>>> Selecting next state in OFS mode...
State selected: ('None.UAS|None.UAC', 12712)
>>> Searching template with no rules
Probability-based selection from templates: ['9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34']
fields_to_fuzz:  [ 0  4  6  7  9 10 11]
>>> FUZZING msg...
>>> SELECTED TEMPLATE: 19
>>> TRANSITION TO STATE: None.UAS|None.UAC
>>> STATUS: OK, TRANSITION: 24;38;19
socket: [Errno 32] Broken pipe in send operation
>>> RESETING MODEL...

[*] Connected to server...
>>> Selecting next state in OFS mode...
State selected: ('START|None.UAC', 4236)
>>> Searching template with no rules
Probability-based selection from templates: ['1']
Traceback (most recent call last):
  File "./pulsar.py", line 115, in <module>
    f.run()
  File "/home/roel/fuzzer/pulsar/pulsar/core/fuzzer.py", line 113, in run
    snd_message = self.lens.transitionSelf()
  File "/home/roel/fuzzer/pulsar/pulsar/core/lens.py", line 895, in transitionSelf
    return self.transition(self.role, True)
  File "/home/roel/fuzzer/pulsar/pulsar/core/lens.py", line 991, in transition
    (state, template, msg, fields, transition) = self._transition_to_state(next_state)
  File "/home/roel/fuzzer/pulsar/pulsar/core/lens.py", line 1037, in _transition_to_state
    self.fuzzer)
  File "/home/roel/fuzzer/pulsar/pulsar/core/lens.py", line 656, in create_fuzzed_message
    fuzz_fields = fuzzer.get_fuzz_fields(next_template.ID)
  File "/home/roel/fuzzer/pulsar/pulsar/core/fuzzer.py", line 337, in get_fuzz_fields
    fuzz_mask_int = self.tracker[template_id]
KeyError: '1'
```

**Comment by RoelVdP** [comment]
Note; the broken pipe error is seen elsewhere too
```
>>> STATUS: OK, TRANSITION: 24;46;11
socket: [Errno 32] Broken pipe in send operation
>>> RESETING MODEL...
```
So it may be/looks like unrelated to the key error.

**Comment by RoelVdP** [comment]
`KeyError: '1'` Also observed

**Comment by hgascon** [comment]
Is the server closing connection because of the fuzzed message?
