### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by CSUer2021** [hgascon/pulsar#33]
May I ask how the case(itunes-xbmc) you gave passed the fuzz test?

When I type the command：pulsar.py -z -m /home/csuerlk/Pulsar/pulsar/models/itunes-xbmc, I encounter the following problem:

Traceback (most recent call last):
  File "pulsar.py", line 115, in <module>
    f.run()
  File "/home/csuerlk/Pulsar/pulsar/pulsar/core/fuzzer.py", line 111, in run
    self.timeout, self.bsize)
  File "/home/csuerlk/Pulsar/pulsar/pulsar/common/networking.py", line 11, in __init__
    self.connection.connect((host, port))
TimeoutError: [Errno 110] Connection timed out

**Comment by hgascon** [comment]
Are you running the application on the specified port? It looks like there is nothing listening.
